// <auto-generated />
namespace lab4_films.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Value : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Value));
        
        string IMigrationMetadata.Id
        {
            get { return "202012201758533_Value"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
